package example:example;

world example-sensors {
    import ariel:wasm-bindings/sensors-api@0.0.1;
    import ariel:wasm-bindings/log-api@0.0.1;
    import ariel:wasm-bindings/time-api@0.0.1;

    export monitor-temperature: func();
}